### ISSUE TITLE
Amelioration WordWrapping 

### ISSUE THREAD

**Issue by IDerr** [IDerr/mahoyo-french-dev#1]

**Comment by IDerr** [comment]
Les points d'interrogation/exclamation passent toujours à la ligne, contrairement à certains traits d'union qui ne permettent pas de passer à la ligne.

**Comment by CasterTM** [comment]
Certains passages à la ligne se font bien trop tôt sans raison. Se peut-il que le wordwrapping compte dans la longueur des mots les commandes entre crochets qui ne s'affichent pas, ce qui déclenche un passage à la ligne anticipé ?
